serhii-londar/open-source-mac-os-apps

README.md

Add Github contributions - GitHub contributions app, for iOS, WatchOS, and OSX.

Add Github contributions

---

README.md

Add AddressGenerator - A macOS app to safely generate cryptocurrency address.
Close #12.

Add Cryptocurrency section

---

README.md

Add RktMachine

---

README.md

Add Many apps
Create keyboard section
Start review Utilities section

Add Many apps

---

README.md

Reaorganize Readme Structure

---

README.md

Add AUHost

---

README.md

https://github.com/alichtman/stronghold
Utilities
Added stronghold, a CLI for easily configuring MacOS security settings.
- [x ] Only one project/change is in this pull request
- [x ] Addition in chronological order (bottom of category)
- [x ] Appropriate language icon(s) added if applicable
- [x ] Has a commit from less than 2 years ago
- [x ] Has a **clear** README in English

Added stronghold and stripped trailing whitespace

---

README.md

add `JSON` as a section in `Editors`, and added `JSON-Splora` to JSON editors 
https://github.com/wellsjo/JSON-Splora
Editors -> JSON
add `JSON` as a section in `Editors`, and added `JSON-Splora` to JSON editors 
popular open source editor that is fun to work on. low barrier to entry. uses modern tools like Electron

add JSON-Splora

---

README.md

Added swift icon to indicate the language used in Pods Updater app.

Add language icon to Pods Updater app.

---

README.md

Fix link redirect for Streaker

Fix link redirect for Streaker

---

README.md

https://github.com/sindresorhus/gifski-app
Graphics
Added the open-source Gifski app.

Add Gifski

---

README.md

Edit apps descriptions
Replace Mac Os X with macOS
Replace "open-source" with "open source"

Remove a/an articles

---

README.md

https://github.com/Microsoft/vscode
IDE
Add VSCode. It is an open source code editor developed by Microsoft.

Add VSCode - Code editor developed by Microsoft.

---

README.md

Theses links wouldn't scroll down. 
Firefox 59 on Linux Mint

Fix broken anchors

---

README.md

Fix Lua language icon for Hammerspoon application

Fix Lua language icon for Hammerspoon application

---

README.md

https://github.com/zeit/hyper
Terminal
Add hyper to terminal section
Because its awesome and fits right in

Add Hyper to terminal section

---

README.md

[Mark Text](https://github.com/marktext/marktext/)
Editors => markdown
Mark Text is realtime preview and use snabbdom as its render engine, it support CommonMark Spec and GitHub Flavored Markdown Spec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/serhii-londar/open-source-mac-os-apps/99)

Add Mark Text to readme

---

README.md

https://github.com/toxblh/MTMR
MacOS app
Small utility for full change and customisation TouchBar using AppleScripts and like system buttons.

Add MyTouchbarMyRules

---

README.md

https://github.com/getinsomnia/insomnia
Web development
Added the open-source Insomnia app. 
Insomnia is a popular Web Development tool.  Insomnia does have a [paid Addons](https://insomnia.rest/pricing/), but I don't think that disqualifies this from the intent of the project, let me know if you think this is an issue.

Add Insomnia

---

README.md

[https://github.com/alvesjtiago/airpass](https://github.com/alvesjtiago/airpass)
Utilities
Status bar Mac app to overcome time constrained WiFi networks.

Added Airpass to utilities

---

README.md

Fixed typo:
developement -> development
Found with: https://github.com/ss18/grep-typos

Enhancement

---

.gitattributes

Add merge attribute for Readme.md according [this discussion](https://github.com/serhii-londar/open-source-mac-os-apps/pull/108).

Add merge attribute for Readme.md

---

README.md

Add chunkwm

---

README.md

https://github.com/gergelysanta/photominer
Images
macOS application for finding all your photos. It will deep-scan selected directories and will display all photos found in them in chronological order. Date is taken from photo's EXIF data or from file creation date if EXIF is not present.

Add PhotoMiner app

---

README.md

https://github.com/chrissimpkins/Crunch
Images
Added Crunch
Great alternative to ImageOptim for PNGs
*(Not applicable; no existing icon, shell app converted to a mac app with [Playtpus](https://github.com/sveinbjornt/Platypus))*

Add Crunch

---

README.md

https://hg.mozilla.org/mozilla-central/
https://firefox.com
Browser
Add the browser Firefox
Because it's awesome

Add Firefox to browsers

---

README.md

https://github.com/glushchenko/fsnotes
Notes
Notes manager for macOS/iOS: modern notational velocity (nvALT) on steroids

Add FSNotes

---

README.md

Adding Oni Editor as an awesome open source MacOS Apps. 
https://www.onivim.io
Editors, IDE
Tries to bring Vim mouse-free adding new editors functionality and keep an IDE appearance

Add oni below Editors#IDE

---

README.md

Rename Regxr to Feather

---

README.md

https://github.com/michaelvillar/timer-app
Productivity

Add a productivity app: Timer

---

README.md

Added KeePassXC to the list
https://keepassxc.org/
Utilities - alongside Macpass
Add KeePassXC to the list

Add keepassxc

---

README.md

Add gitter.im chat link
Add ci status badge
Move awesome badge to other

Add gitter.im chat link

---

README.md

https://ingmarstein.github.io/Monolingual/
Utilities
Add Monolingual to utilities

Add Monolingual

---

README.md

* https://www.qbittorrent.org/
* https://www.tribler.org/
* https://deluge-torrent.org/
* https://github.com/qbittorrent/qBittorrent/blob/master/README.md
* https://github.com/Tribler/tribler/blob/next/README.rst
* https://git.deluge-torrent.org/deluge/tree/README.rst
* file-sharing

qBittorrent, Tribler, Deluge

---

README.md

Add GithubListener app
https://github.com/ad/GithubListener
Git
Simple macOS app that will notify about new commits to watched repositories.

Add GithubListener

---

README.md

Add [Cerebro app](https://cerebroapp.com)
https://github.com/KELiON/cerebro
Productivity

Add Cerebro

---

README.md

https://github.com/cemolcay/ChordDetector
Music
Only one project/change is in this pull request

Add ChordDetector

---

README.md

Please merge #174 first, thanks!
https://github.com/cemolcay/PercentCalculator
Utilities
Only one project/change is in this pull request

Add PercentCalculator

---

README.md

Added float coin app to cryto currencies section
Its a light weight app that supports many exchanges

Added floatcoin

---

README.md

Added nodeScratchpad to Development/Web development section
https://github.com/vsaravind007/nodeScratchpad
Development / Web Development
Added nodeScratchpad to the list

Added nodeScratchpad

---

README.md

Close #145 
https://github.com/standardnotes/web
Notes
A safe and private place for your life's work. This is the Standard Notes web app. | https://standardnotes.org

Add standard notes

---

README.md

Add Inkscape
Close #104 
https://gitlab.com/inkscape/inkscape
Graphics
Inkscape is professional quality vector graphics software

Add Inkscape

---

README.md

Close #42 
https://github.com/blockstack/blockstack-browser
Utilities
added from issue [#42](https://github.com/serhii-londar/open-source-mac-os-apps/issues/42)

add Blockstack Browser from issue #42

---

README.md

Remove Google-Docs-for-Mac

---

README.md

Add KeeWeb

---

README.md

Remove Sidetalk

---

README.md

Close #53 
https://github.com/xor-gate/syncthing-macosx
Other
Frugal native Mac OS X Syncthing application bundle

Add syncthing-macosx

---

README.md

https://github.com/ivoronin/ArchiveMounter
Utilities
Mounts archives like disk images

Add Archive Mounter

---

README.md

https://github.com/quickwords/quickwords
**EDIT:** Productivity
Added Quickwords, a new, open-source productivity app, that helps you execute tedious tasks very quickly.

Added Quickwords

---

README.md

**Artify**
https://github.com/NghiaTranUIT/artify-macos
Wallpaper
A macOS X application for bringing dedicatedly 18th century Arts to everyone
open-source-mac-os-apps is the best place to share and find new hidden gem : ]

Add Artify

---

README.md

* Project URL: https://sqlitebrowser.org
* Category: Database
* Description: SQLite database management GUI

Add DB Browser for SQLite

---

README.md

Reorder alphabetically - browser

---

README.md

Reorder alphabetically - chat

---

README.md

Reorder alphabetically - cryptocurrency

---

README.md

Reorder alphabetically - database

---

README.md

Reorder alphabetically - downloader

---

README.md

Reorder alphabetically - editors

---

README.md

Reorder alphabetically - extensions, finder, games, graphics

---

README.md

Reorder alphabetically - ide, images, keyboard, mail

---

README.md

Reorder alphabetically - menubar, music, news, notes

---

README.md

Reorder alphabetically - sharing files, social networking, streaming, system

---

README.md

Reorder alphabetically - video, wallpaper, window management, icon links

---

README.md

Fix accidental wrong placement for UnMuteMic in Audio section

---

README.md

Reorder alphabetically - other

---

README.md

https://github.com/mpv-player/mpv
Player
Video player based on MPlayer/mplayer2.

Add mpv video player

---

README.md

https://lunarapp.site
Utilities
Added Lunar app to the utilities category. 
Probably, there aren't a lot of people who would need this app. But for those who do, it is a lifesaver.

Add Lunar app

---

README.md

https://github.com/vishaltelangre/Kyapchar
Screencasting, Utility
Simple screen and microphone audio recorder for macOS written in Swift.

Add Kyapchar app

---

README.md

https://github.com/ishuah/bifrost
Terminal
A tiny terminal emulator for serial port communication (macOS/Linux)
Bifrost supports USB type-C out of the box (2016+ Macbook friendly) unlike most serial port terminal emulators.
There is no Golang icon yet

Add Bifrost

---

README.md

Remove "open source" from app descriptions
Remove "application that"

Description update

---

README.md

Move to "Social Networking" section
Just like Caprine and Goofy

Move Messenger to "Social Networking" section

---

README.md

Awesome lint fixes

---

README.md

https://github.com/mczachurski/wallpapper
Images
wallpapper is a console application for creating dynamic wallpapers for Mojave.

Add wallpapper

---

README.md

Hello @serhii-londar, I'm not sure about this change or about how it should be. But what do you think about adding the link to the contributing guidelines to README?

Add the link to CONTRIBUTING.md

---

README.md

Added taskbook cli app on productivity category.
- https://github.com/klauscfhq/taskbook
- Productivity
- Tasks, boards & notes for the command-line habitat.

Add taskbook

---

README.md

https://github.com/igorkulman/iOSLocalizationEditor
Devellopment/iOS
Simple macOS editor app to help you manage iOS app localizations by allowing you to edit all the translations side by side

Add Localization Editor

---

README.md

https://github.com/brentsimmons/NetNewsWire
News
It’s a free and open source feed reader for macOS.

Add NetNewsWire

---

README.md

Adding my application Quickeys to the list of apps.
https://github.com/alexrosenfeld10/Quickeys
Menu bar applications
Not much to describe, just added the entry to the `README.md` as per instructions.
I haven't found any apps that accomplish the same functionality.

Adding Quickeys

---

README.md

Update link for galeri app

---

README.md

https://github.com/railsware/upterm
Terminal
Add another terminal application.
Upterm (formerly Black Screen) is an IDE in the world of terminals.

Add Upterm

---

README.md

https://github.com/Yasumoto/ChefInspector
Development -> Other
Add an application for querying your Chef Server (both nodes and their attributes).
A good DevOps-y application for macOS.

Add ChefInspector

---

README.md

new suggestion: itsycal(tiny free calendar)

---

README.md

Fix contributors image

---

README.md

Add TableTool
https://github.com/jakob/TableTool
Editors/CSV
Simple CSV editor for the macOS.

Add TableTool

---

README.md

Add InjectionIII
Close #307 
https://github.com/johnno1962/InjectionIII
Development/macOS/iOS
InjectionIII - overdue Swift4 rewrite of Injection

Add InjectionIII

---

README.md

Fix name for PushNotifications app

Fix name for PushNotifications app

---

README.md

add gSwitch
https://github.com/CodySchrank/gSwitch
Menubar
gSwitch is intended to replace the functionality provided by gfxCardStatus since it is no longer maintained.

add gSwitch

---

README.md

Line | Status | Link
| ---: | :----: | --- |
444 | [301](https://httpstatuses.com/301) | https://github.com/xor-gate/syncthing-macosx redirects to<br>https://github.com/syncthing/syncthing-macos

Fix link issue

---

CONTRIBUTING.md

Just some minor edits to CONTRIBUTING.md

Minor spelling / grammar fixes

---

applications.json

Add Letters

---

Sources/test.swift

Remove Sources folder

---

applications.json

<table>
<thead>
<tr>
<th width="50"></th>
<th width="100%" data-danger-table="true" data-kind="Warning">
1 Warning
</th>
</tr>
</thead>
<tbody>
<tr>
<td>:warning:</td>
<td data-sticky="false">Found 10 link issues, a project collaborator will take care of these, thanks :)</td>
</tr>
</tbody>
</table>
Line | Status | Link
| ---: | :----: | --- |
3399 | [404](https://httpstatuses.com/404) | https://raw.githubusercontent.com/klauscfhq/ao/master/media/list-navigation.gif 
3400 | [404](https://httpstatuses.com/404) | https://raw.githubusercontent.com/klauscfhq/ao/master/media/compact-mode.png 
3402 | [404](https://httpstatuses.com/404) | https://raw.githubusercontent.com/klauscfhq/ao/master/media/ao-vibrant.png 
3403 | [404](https://httpstatuses.com/404) | …

Fix image link issues

---

applications.json

https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation
iOS / macOS
AppBox is a tool for iOS developers to build and deploy Development, Ad-Hoc and In-house (Enterprise) applications directly to the devices from your Dropbox account.

Added AppBox Screenshot

---

applications.json

Links 
1. [L0805] 404 https://github.com/simplerocket-llc/OpenCashew  
2. [L1893] 301 https://github.com/lukakerr/twig  → https://github.com/lukakerr/Pine 
3. [L1897] 404 https://raw.githubusercontent.com/lukakerr/twig/master/./Twig/Assets.xcassets/AppIcon.appiconset/twig-512.png

Fix link issues

---

README.md

Signed-off-by: Seonggwon Yoon <keyakoto@gmail.com>
Just fix broken icon

Fix broken icon

---

applications.json
categories.json

Add Touch Emoji
https://github.com/lm-a/touch-emoji
Utilities
Touch Emoji — emoji picker for MacBook Pro Touch Bar

Add Touch Emoji

---

applications.json

add calibre .
It is cross platform e-book manager
https://github.com/kovidgoyal/calibre
Utilities
just change **applications.json**
```json
{
"short_description" : "cross platform e-book manager.",
"categories" : [
"Utilities"
],
"repo_url" : "https://github.com/kovidgoyal/calibre",
"title" : "calibre",
"icon_url" : "",
"screenshots" : [
"https://github.com/kovidgoyal/calibre/blob/master/resources/images/lt.png"
],
"official_site" : "",
"languages" : [
"python"
]
}
```
It's a powerful e-book manager.

Add Calibre

---

applications.json

https://github.com/vpeschenkov/Predator
`screensaver`

Add Predator

---

applications.json

docs: fix typo

---

applications.json

```
> Links 
1. [L0012] 404 https://github.com/friedrichweise/wechsel/blob/master/screenshot.png 
```

Update the "wechsel" screenshot link

---

applications.json

https://github.com/amiantos/lifesaver
```screensaver```
An abstract screensaver based on Conway's Game of Life implemented with SpriteKit

Add "Life Saver"

---

applications.json

Remove Dozer

---

applications.json

https://github.com/rxhanson/Rectangle
window-management
Rectangle is a window manager heavily based on Spectacle, written in Swift.
Spectacle (also in this list) hasn't been maintained in ~2 years. Rectangle brings almost all of the functionality of Spectacle into Swift and adds in some more updates. The custom (and often buggy) shortcut recorder in Spectacle is replaced with the popular and stable MASShortcut library.

Add Rectangle app to the list

---

applications.json

Update some info about IINA. 
Added official site url and short description. Icon url is the one [used in their readme](https://github.com/iina/iina/blob/develop/README.md#L2)

Update IINA info

---

applications.json

https://github.com/sindresorhus/quick-look-plugins
finder
List of Quick Look plugins was added.
The proposed set represents useful plugins for QuickLook.

Add Quick Look plugins

---

applications.json

https://github.com/MitMaro/git-interactive-rebase-tool
Git
Simple native CLI tool for working with git interactive rebase todo files.
The tool has a decent user base and is available on homebrew for easy installation on MacOS. I am also the author, so I have a bit of bias in thinking that it is awesome!

Add Git Interactive Rebase Tool

---

applications.json
categories.json

http://www.cti.gov.br/invesalius/
Images and Medical (I've added it to categories.json).
Add InVesalius to the list
InVesalius is one of the main medical imaging software to Mac, Windows and Linux.

Add InVesalius

---

applications.json

* https://github.com/bitwarden/desktop
* https://bitwarden.com/
Utilities
Add Bitwarden to `applications.json`, a cross-platform password management solutions for individuals, teams, and business organizations.
Bitwarden is 100% open source software. The source code for Bitwarden is hosted on GitHub and everyone is free to review, audit, and contribute to the Bitwarden codebase.
Creators believe that being open source is one of the most important features of Bitwarden. Source code transparency is an absolute requirement for software solutions like Bitwarden.

Add Bitwarden

---

README.md

Correcting misspelling of percents

Change parcents to percents

---

applications.json

https://github.com/yonilevy/automute
Audio
Automatically mute the sound when headphones disconnect / Mac awake from sleep.

Add AutoMute

---

applications.json

https://github.com/fphilipe/PageExtender.app
Extension
This adds PageExtender to the list.

Add PageExtender

---

applications.json

https://github.com/obsproject/obs-studio
Streaming
Free and open source software for live streaming and screen recording.
Free and open source software for live streaming and screen recording.

Add OBS Studio

---

applications.json

This project is not maintained anymore. Since Inbox is closed this project has to be closed as well.

Remove Inboxer

---

applications.json

This project is not maintained anymore. Since Inbox is closed this project has to be closed as well.

Remove gInbox

---

.travis.yml
applications.json

https://github.com/powershell/powershell
Utilities
PowerShell is a shell.
> PowerShell Core is a cross-platform (Windows, Linux, and macOS) automation and configuration tool/framework that works well with your existing tools and is optimized for dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object models. It includes a command-line shell, an associated scripting language and a framework for processing cmdlets.

Add PowerShell

---

applications.json

https://github.com/tigase/beagle-im
Chat
Adding BeagleIM xmpp client
Well, it's open-source, it's for macOS and it's awesome

add BeagleIM xmpp chat app

---

applications.json

https://github.com/cryptomator/cryptomator
Security
Added Cryptomator to `applications.json`

Added Cryptomator

---

applications.json

https://www.gnugk.org
Video
Video Conferencing server (daemon) for H.323 terminals and room systems

add GNU Gatekeeper

---

applications.json

Fix categories for Xpiks

---

applications.json

Adding Super Productivity
http://super-productivity.com
Super Productivity
Because I love it!
- [x ] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [ x] Only one project/change is in this pull request
- [ x] Screenshots(s) added if any
- [ x] Has a commit from less than 2 years ago
- [x ] Has a **clear** README in English

add super productivity

---

applications.json

Calculeta is a calculator for macOS which working on statusbar. 
https://github.com/varol/Calculeta
Utilities
Productivity
Calculeta is a calculator for macOS which working on statusbar. It developed with Swift.

Calculeta added on the list

---

applications.json

Added file sharing application
https://nitroshare.net
Sharing Files
NitroShare is designed to make transferring files from one device to another extremely simple

Added NitroShare

---

applications.json

[https://github.com/khrykin/StrategrDesktop](https://github.com/khrykin/StrategrDesktop)
[https://khrykin.github.io/strategr](https://khrykin.github.io/strategr)
Productivity
Stategr helps you maximize your productivity, giving you the quickest and most effective way to time-box your day with strategies. More info on the website.
Well, cause... it's awesome!

Added Strategr - no-fuss time management app

---

applications.json

https://exifcleaner.com
Images
Remove image metadata with drag and drop, multi-core batch processing, and dark mode.
Supports macOS's dark mode.

Add ExifCleaner

---

applications.json

https://github.com/musa11971/Music-Bar/
Music, audio, menubar, utilities
Added Music Bar to the applications.

Added Music Bar application

---

applications.json

Remove Alloy

---

.github/ReadmeGenerator.xcodeproj/project.pbxproj
.github/ReadmeGenerator.xcodeproj/xcshareddata/xcschemes/ReadmeGenerator.xcscheme
.github/main.swift

this will fix #494:
- fix userscheme
- update generator to support any kind of paths (absolute and relative
paths) 
- made xcodeproj runnnuble by anyone

Improve generator script

---

applications.json

https://github.com/nbolar/PlayStatus
Audio, Menubar, Music
Added one new app called PlayStatus to the applications.json file.

Added PlayStatus to applications.json

---

applications.json

https://github.com/kamranahmedse/pennywise
browser, productivity
Pennywise opens any website or media in a small floating window that remains on top of all other applications.  
Watching tutorial while you code? Open the video in Pennywise and keep it in front of you

Add Pennywise

---

applications.json

https://github.com/jet8a/pomodoro-cycle-app
Productivity
Pomodoro cycle tracker

Add pomodoro cycle app

---

applications.json

Application name was way larger. Shorted it out. So can read clearly.

Update app name

---

applications.json

https://github.com/simple-login/
https://simplelogin.io
Mail
Open source email alias solution to protect your email address
The project is 100% open source: the back-end, Mac app (Safari extension) and Chrome/Firefox extensions are open source.
- [X ] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [ X] Only one project/change is in this pull request
- [ X] Screenshots(s) added if any
- [ X] Has a commit from less than 2 years ago
- [ X] Has a **clear** README in English

Add SimpleLogin to mail software list

---

README.md
applications.json

added Syncalicious project

---

applications.json

Update application language

---

PULL_REQUEST_TEMPLATE.md
applications.json

[upterm](https://github.com/railsware/upterm)
Terminal 
Project is depreciated

Remove Upterm

---

applications.json

https://github.com/maoyama/GitBlamePR
- git
Mac app that shows pull request last modified each line of a file.

Add GitBlamePR

---

README.md
applications.json

https://github.com/amirdew/CollectionViewPagingLayout
Development > iOS/macOS
Add Layout Designer repo to the `applications.json` file
Its a simple but powerful tool for making complex layouts for UICollectionView.
Using the app is very easy since it shows a preview in real-time and generates code.
so it's an awesome macOS app that helps developers to make awesome apps!

Add Layout Designer (a macOS app that makes layout for UICollectionView)

---

applications.json

Spotter
[https://github.com/spotter-application/spotter](https://github.com/spotter-application/spotter)
Productivity, Utilities, System
Spotter is a productivity tool, the main function is to search and launch external application actions and applications themselves. (e.g. switch the next song or set a timer...) so you can stay focused on your current task. Kind of spotlight or alfred alternative.

Add spotter

---

applications.json

https://gaphor.org
Graphics
Gaphor is a UML and SysML modeling application written in Python. It is designed to be easy to use, while still being powerful. 
It is a great open source app for macOS in an area that isn't yet on your list, I think it would be a good addition. They just released version 2.0.0, so now might be a great time.

Add Gaphor - the simple modeling tool

---

applications.json

Add IDE -vim

---

applications.json

https://github.com/dwarvesf/hidden
Menubar
Add Hidden Bar app.
Hidden Bar is a great open source alternative to Bartender.

Add hidden bar

---

applications.json

https://github.com/sfsam/Itsycal
Menu bar, productivity
A calendar that lives in the menu bar.
Itsycal is a great system clock alternative and gives quick access to the calendar.

Add itsycal

---

applications.json

https://github.com/vector-im/element-web
Riot.im has rebranded to Element.

Rename Riot.im to Element

---

applications.json

https://jintin.github.io/Swimat/
Extension
An Xcode formatter plug-in to format your swift code.

Add Swimat

---

applications.json

https://github.com/mattiarossini/MinimalClock
Screensaver
Simple and elegant screensaver for MacOS that displays the time.

 Add MinimalClock

---

applications.json

https://github.com/hbowie/notenik-swift
Notes, Markdown
Added the Notenik app, and fixed a typo in the app above. 
It's an open source note-taking app written in Swift for macOS. 
- [ x] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [x ] Only one project/change is in this pull request
- [x ] Screenshots(s) added if any
- [x ] Has a commit from less than 2 years ago
- [ x] Has a **clear** README in English

Added Notenik

---

applications.json

https://github.com/swiftbar/SwiftBar
menubar
Powerful macOS menu bar customization tool

Adding SwiftBar

---

applications.json

https://github.com/manindaniil/market-bar
Menubar
Tiny stocks watcher for the menu bar.

Add Market Bar

---

applications.json

https://github.com/RobotsAndPencils/XcodesApp
Development > iOS / macOS 
I'm a developer of the tool, and I think it's really useful for developers that use Xcode, and it's a good example of an open-source SwiftUI app on macOS.
_Note: There are two commits here. The first one fixes an issue (too many quote characters, and mixed indentation) in the entry for MPV that was at the end of the file, right before where the new entry is._

Add Xcodes.app

---

applications.json

https://github.com/simplelocalize/simplelocalize-cli
Web development 
We use it to translate e-mails which are sent from NodeJS backend. 👍  Open source tool for finding i18n keys in software projects.
It's native macOS app and it's useful in web development

Add SimpleLocalize

---

applications.json

PR duplicate of #651. (cause redoing all the work is faster then merging...
Suggestion: you should add a Travis CI step to check for json validity ;)

Maintenance PR. Fixes broken json syntax and uniforms whitespace

---

applications.json

https://github.com/nikolaeu/numi
utilities
Project is not open source the git repository only contains plug-ins from the community to the closed source application.

Remove numi

---

applications.json

https://hg.mozilla.org
browser
Added Firefox
See https://hg.mozilla.org/mozilla-central/file/tip/README.txt for the readme

Added Firefox

---

applications.json

Added new app Condution
https://www.condution.com
Productivity
Create tasks, manage due dates, and filter with powerful perspectives.
- [x ] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [x ] Only one project/change is in this pull request
- [ x] Screenshots(s) added if any
- [ x] Has a commit from less than 2 years ago
- [ x] Has a **clear** README in English

Added Condution app

---

applications.json

https://www.beekeeperstudio.io
Database
Adds entry for Beekeeper Studio, a SQL database editor and manager GUI app.
Beekeeper Studio is the best GUI DB app I've used so far – setup is easy, it's aesthetically well-designed, and it supports a variety of SQL implementations, so I don't need to install a separate app for each one.

feat: Add Beekeeper Studio

---

.github/main.swift

Fix issue with shell icon

---

applications.json

Fix CloudyTabs language

---

applications.json

https://github.com/arsenetar/dupeguru/
Finder, Utilities
dupeGuru is a tool to find duplicate files on your computer. It can scan using file names and file contents.
Good duplicate finder that works with both file names and file contents. Also has music and picture specific scanning modes.

Add dupeGuru

---

applications.json

https://github.com/JetBrains/intellij-community
IDE
Open Source version of IntelliJ IDEA Java IDE

Add IntelliJ IDEA Community Edition

---

applications.json

https://github.com/FreeCAD/FreeCAD
Graphics, Other Development
Adding FreeCAD an open-source 3D parametric modeler

Add FreeCAD

---

applications.json

Make drag-and-drop easier using DropPoint. DropPoint helps to drag content without having to open side-by-side windows.
An open source alternative to Drop Over.
https://github.com/GameGodS3/DropPoint
Productivity
Utility
Added DropPoint to applications.json as indicated in the Contributing Guidelines.

Add DropPoint

---

.github/main.swift
applications.json

type_script -> typescript

---

applications.json

https://www.thunderbird.net/
- Mail
- Chat
Privacy oriented, extensible, performant.

Add Thunderbird, mail

---

applications.json

https://krita.org
- Images
- Graphics

Add Krita, graphics, images

---

applications.json

https://www.blender.org
Graphics

Add Blender 3D, graphics

---

applications.json

https://github.com/swiftyfinch/Rugby
Utilities
I've added my open source project 🏈 Rugby to Tools category.
I want to share my work with all iOS community

Add 🏈 `Rugby` utility

---

applications.json

Deleted Kaktus from the Browser List

---

applications.json

An open-source game with mac-os support
website: https://www.widelands.org
github: https://github.com/widelands/widelands
Games
I have added Widelands, an open-source macos game, into this list. 
Because it is on macOS, open source, and awesome?

Add Widelands

---

.github/workflows/main.yml
.github/workflows/pr.yml

This updates the used checkout action in the workflows to the latest major version.

Bump actions/checkout to version 3

---

README.md
applications.json

[nvm github](https://github.com/nvm-sh/nvm)
Utilities
Node Version Manager

feat: add nvm (node version menager)

---

applications.json

https://github.com/sqlectron
Database/Productivity
SQLectron is a  simple and lightweight SQL client desktop/terminal
with cross-database and platform support. 
It is an open-source and cross-database client for macOS users which solves the requirement of multiple database clients. The nice UI also makes it user-friendly.

Added SQLectron

---

README.md

Changed language icon designs from the simple list to the badge form.

Update READE's language icons #572

---

applications.json

close #749
https://github.com/CodeEditApp/CodeEdit
- editors
- ide
Added CodeEdit information to `applications.json`
This project is an editor that allows the Xcode development experience to be enjoyed for projects outside of the Apple platform.

Add CodeEdit app

---

README.md
applications.json

[#637] Add Monitor Bar app to Menu Bar list
[Monitor Bar](https://github.com/tidiemme/monitorbar)
Menubar
[#637] Add Monitor Bar app to Menu Bar list
The app supports three modes, compact, normal, extra. It monitors battery, Disk, Memory, CPU, Network bandwidth, Wi-Fi.

[#637] Add Monitor Bar app to Menu Bar list

---

README.md
applications.json

https://github.com/aonez/Keka
Utility
Keka is a full featured file archiver, as easy as it can be.

Add Keka app

---

applications.json

https://github.com/AuroraEditor/AuroraEditor
Text
Lightweight Code Editor (IDE) for macOS.
We want to let the world know about this awesome project

Add AuroraEditor

---

applications.json

https://github.com/spicetify/spicetify-cli
Music
I added Spicetify to the `application.json`

Added Spicetify

---

applications.json

Fix categories for AuroraEditor

---

applications.json

https://github.com/adium/adium
Chat
I added a resource named "Adium" in chat section by editing applications.json file.
Adium is a free instant messaging application and is one of the oldest and widely used chat application for macOS that can connect to XMPP (Jabber), IRC and more.

Added a chat resource

---

applications.json

https://imhex.werwolv.net/
Editors, IDE
Added ImHex to this list
Imho, for reverse-engineering and security investigators is a great tool

Added ImHex to Editors section

---

applications.json

Added the Geany Editor, or Lightweight IDE.
[https://github.com/geany/geany](https://github.com/geany/geany)
Editors
Updated applications.json with the information for Geany.

Add Geany Lightweight IDE/Editor
