README.md

Add Platypus - Mac developer tool that creates application bundles from command line scripts. language - Objective-C.
close #8 #7

Add Platypus

---

README.md

Include the opensource chatting application Signal Desktop
https://github.com/signalapp/Signal-Desktop
https://signal.org/download/
Chat
Signal is an iOS/Android messaging app for simple private communication with friends. Signal Desktop is an Electron application that links with Signal.

Add  Signal Desktop

---

README.md

https://github.com/wireapp
Chat
Add the secure chat app Wire to the list of open source chat apps.
It's a nice secure chat app that is completely open source. (server and clients)

Add the chatapp wire

---

README.md

https://github.com/lettier/gifcurry
https://lettier.github.io/gifcurry
Graphics
Adds the open source macOS app Gifcurry made with Haskell, GTK+, and GStreamer.
[Why do I need Gifcurry?](https://github.com/lettier/gifcurry#what-do-i-need-gifcurry-for)
:+1:

Adds Gifcurry.

---

README.md

https://github.com/BafS/Material-Colors-native
Graphics
Choose your Material colors and copy the hex code.

Add Material Colors native app

---

README.md

https://github.com/archagon/sensible-side-buttons
Utilities
A small menu bar utility that lets you use your third-party mouse's side buttons for navigation across a variety of apps.
SensibleSideButtons is one of the only ways to get native, near-universal back/forward behavior for a mouse's side buttons in macOS. Most other approaches involve keyboard shortcuts which don't work very well. (The behavior and technology are described in detail on the [project homepage](http://sensible-side-buttons.archagon.net).)

Add SensibleSideButtons

---

README.md

https://github.com/docterd/MusaicFM
Screensaver
Added MusaicFM to screensavers
MusaicFM is a iTunes Screensaver clone for Spotify and Last.fm written in Objective-C.

Added MusaicFM to screensavers

---

README.md

https://github.com/Kwpolska/DisplayMenu
Utilities
Added [DisplayMenu](https://github.com/Kwpolska/DisplayMenu), a simple (bare-bones) macOS menubar extra to apply display presets.
Not that many projects do Swift *and* Quartz APIs. It was created because [Apple stole the real display menu from me](https://chriswarrick.com/blog/2017/06/24/apple-broke-the-display-menu-so-i-wrote-my-own/).

Add DisplayMenu

---

README.md

remove the extra "which"
There was an extra "which"

typo. remove extra "which" from readme

---

README.md

The table of contents section was missing the "Browser" section, and wanted to make it easier to navigate straight to it from the `README.md` file!

Adding "Browser" to the "Contents" section

---

README.md

http://gcollazo.github.io/mongodbapp/
Other
The easiest way to get started with mongoDB on the Mac.
It has a cool update script that makes building and maintaining this kind of app really simple.

Adds mongoDB.app

---

README.md

http://jpadilla.github.io/redisapp/
Other
The easiest way to get started with Redis on the Mac.
It has a cool update script that makes building and maintaining this kind of app really simple.

Add Redis.app

---

README.md

Add React Native Debugger, desktop app that helps in React Native development.
[https://github.com/jhen0409/react-native-debugger](https://github.com/jhen0409/react-native-debugger)
Development / Other
This is a standalone app for debugging React Native apps:
* Based on official Remote Debugger and provide more functionally.
* Includes React Inspector from react-devtools-core.
* Includes Redux DevTools, made the same API with redux-devtools-extension.

Add React Native Debugger

---

README.md

The entry for Flycut had an abundant space between name and link causing it to not be rendered as two things: the name and the link separately.
not applicable
none - just a bugfix
see above.

Fix typo for Flycut

---

README.md

**Keka** and **The Unarchiver** are tools to compress/uncompress, zip/unzip, etc.:
* They should be in the same category.
* That's not affecting the system so it doesn't belong to _System_ category.
* Being in _Productivity_ or _Utility_ is a matter of choice (if you prefer Productivity, I'll update the Pull Request)

regrouping archivers

---

README.md

Removing app during DMCA takedown.
It may be re-added in the future if the app is back, but for now it's unavailable.

removing app during DMCA takedown

---

README.md

The removed line pointed to https://github.com/Majirefy/BingPaper, which is no longer maintained. The new source is at https://github.com/pengsrc/BingPaper, which is already entry number 2 on this list.

Remove duplicate BingPaper pointing to old repo

---

README.md

https://github.com/mortenjust/androidtool-mac
Utilities
One-click screenshots, video recordings, app installation for iOS and Android

Add Android tool for Mac

---

README.md

Updated icon images/links so when Markdown is transformed - when mousing over an language icon the description is revealed.
```
N/A
```
```
N/A
```
Updated icon images/links so when Markdown is transformed - when mousing over an language icon the description is revealed.

Add titles to language icons

---

README.md

Current URL is just fork. At https://balance.io you can find the right GitHub link.

Corrects link for balance-open project

---

README.md

https://github.com/pencil2d/pencil
Graphics
Pencil2D lets you create traditional hand-drawn animation (cartoon) using both bitmap and vector graphics on Windows, MacOS and Linux. Pencil2D is free and open source. http://pencil2d.org

Add Pencil2D Animation

---

README.md

[Maccy](https://github.com/p0deje/Maccy)
Productivity
Adds [Maccy](https://github.com/p0deje/Maccy), lightweight search-as-you-type clipboard manager for macOS.

Add Maccy clipboard manager

---

README.md

Close #49 
https://github.com/josh-/CloudyTabs
Menubar
add CloudyTabs from issue [#49](https://github.com/serhii-londar/open-source-mac-os-apps/issues/49)

add cloudy tabs

---

README.md

https://github.com/stephanebruckert/ShazamScrobbler
Audio
Scrobble vinyl, radios, movies to Last.fm – ShazamScrobbler was created for people who use Shazam to identify songs played around their Mac and would like to keep an updated playback history using Last.fm's scrobbling service.
For Last.fm and Shazam lovers – only available on Mac

Add ShazamScrobbler

---

README.md

Add macOrganizer app
https://github.com/shubhambatra3019/macOrganizer
Productivity
macOrganizer is a macOS app that helps you organize files or remove unnecessary files.

Add macOrganizer

---

README.md

https://riot.im
https://github.com/vector-im/riot-web
Chat
Adds Riot.im to the Chat category.
Apache licensed Electron client for decentralised, end-to-end encrypted communication via the Matrix protocol.

add Riot.im (collaboration client for the Matrix.org protocol)

---

README.md

https://github.com/z-------------/cumulonimbus redirects to https://github.com/z-------------/CPod

Fix link redirection issue

---

README.md

Several obviously database related entries are presently filed under "Other".
This PR moves them into a new "Databases" section.  Seems like the right
thing to do. :smile:
* Nope.  It's a new category, so the entries have been moved into it in alphabetical order.
- [  ] Has a commit from less than 2 years ago
* Doesn't seem relevant for this PR. :wink:
* Also doesn't seem relevant for this PR.

Move several entries to new "Database" section

---

README.md

https://matrix.org redirects to https://matrix.org/blog/home

Fix Link issue

---

README.md

Add my text editor Noto.
https://github.com/brunophilipe/Noto
Editors/Text
A simple plain text editor for macOS with customisable UI themes.
Because it is awesome 😄

Add Noto plain text editor

---

README.md

https://github.com/ersel/spotify-cli-mac
Music
Lets you control spotify from your terminal. You can also set genius integration to display lyrics.
Because Mac Os users likes to 👂 🎶

Add spotify-cli-mac

---

README.md

Reordering items alphabetically.
The icons and contents section both turned out to have edge cases.
* The ordering of the "C" letter icons is just my best guess.  "Should be ok". :smile:
* Under the Development heading of the Contents, "Other" is manually in the last spot on purpose.  That's just because it's traditional to put the exception/catch-all ("Other" or "Misc") at the end of lists. :smile:

Reorder alphabetically - icons, contents, audio

---

README.md

Changing Markr to Twig (the successor to Markr)
https://github.com/lukakerr/twig
Editors -> Markdown
Changed the name and URL of Markr to Twig
Already included, just switched projects

Change markr to twig (new project)

---

README.md

GitX is referencing a fork that has been inactive for 4 years instead of the current mainstream Fork.
This updates the repo url.
https://github.com/gitx/gitx

Switch GitX to the current active fork

---

README.md

The JS icon was missing from `browserosaurus`.

Added JS icon to `browserosaurus`

---

README.md

added pianobar console player for pandora.com
https://github.com/PromyLOPh/pianobar/tree/master/src
Audio
added pianobar console player for pandora.com

adding pianobar

---

README.md

https://github.com/Mortennn/FiScript
Finder
Added FiScript which lets you execute custom scripts from the MacOS context menu (CTRL+click) in Finder. 
It is an unique application which i think people will enjoy.

Add FiScript

---

README.md

This repo is the primary development home for OpenShot Video Editor (version 2+), a PyQt video editing application which utilizes the powerful libopenshot C++ library.
Close #259 
https://github.com/OpenShot/openshot-qt
Video
Easy to use, quick to learn, and surprisingly powerful video editor.

Add OpenShot

---

README.md

https://github.com/neilalexander/seaglass
Chat
Seaglass is a native Matrix client for macOS
The only other matrix client on this list is an electron app.

Add Seaglass

---

README.md

https://github.com/jake-101/android-messenger-mac
Chat
Mac app wrapper around Google's stand-alone Android Messenger.
I haven't seen any other wrappers for Google's SMS web app for Mac. It has been very useful for me so I thought I'd share it with the community.
- [ x] Only one project/change is in this pull request
- [ x] Addition in alphabetical order
- [ x] Appropriate language icon(s) added if applicable
- [ x] Has a commit from less than 2 years ago
- [ x] Has a **clear** README in English

Added Android Messenger Mac to chat section

---

README.md

The app no longer works in macOS High Sierra or macOS Mojave
https://github.com/codykrieger/gfxCardStatus/
Menubar
The app has not correctly worked since macOS 10.9 and it appears that it is no longer being maintained.  This can be seen by the multiple issues spanning a couple years on github.
- [X ] Only one project/change is in this pull request
- [X ] Deletion in alphabetical order

remove gfxCardStatus

---

README.md

Solves #218 
No image icon was added because Emacs is written in Emacs Lisp
https://www.gnu.org/software/emacs/ but source hosted at https://git.savannah.gnu.org/cgit/emacs.git
Editors/Text
- [ x] Only one project/change is in this pull request
- [x ] Addition in alphabetical order
- [x ] Has a commit from less than 2 years ago
- [ x] Has a **clear** README in English

Add Emacs text editor

---

applications.json

https://github.com/dteoh/devdocs-macos
Other
Added a link to DevDocs for macOS app.
This app lets developers use [DevDocs](https://devdocs.io) as a standalone tool. It is a FOSS alternative to Dash.

Add DevDocs for macOS

---

.travis.yml
applications.json

Add http://joshparnham.com to the whitelist.
Issues :
> Links 
1. [L2674]  http://joshparnham.com/projects/cloudytabs/CloudyTabs.png Failed to open TCP connection to joshparnham.com:80 (getaddrinfo: nodename nor servname provided, or not known) 
2. [L3452] 301 https://github.com/abhishekbanthia/Clocker  → https://github.com/n0shake/Clocker 
3. [L5100] 503 https://www.artstation.com/artwork.rss

Fix link issues.

---

applications.json

https://github.com/Studio3T/robomongo
database
Robo 3T (formerly Robomongo) is the free lightweight GUI for MongoDB enthusiasts.

add Robo 3T (formerly Robomongo)

---

README.md

Just the title. Very minor change.

Fix spelling "parcents" -> "percentages"

---

applications.json

https://github.com/liamrosenfeld/Iconology
images
Added the icon generator app 'Iconology' to the image section.
It gives developers a method to quickly create icons from glyphs without the need to pay for any pro tools. It also integrates with Xcode (by automatically generating the import JSON) and can export additional filetypes (icns and ico) that many pro tools, such as Photoshop and illustrator, do not support without additional scripts.

Add Iconology

---

applications.json

https://github.com/jwise/HoRNDIS
system
Android USB tethering driver for macOS
It gives you the opportunity to use your Android phone's native USB tethering mode to get Internet access.

Add HoRNDIS

---

applications.json

https://github.com/zagahr/Conferences.digital
Video
Conferences.digital is the best way to watch the latest and greatest videos from your favourite developer conferences for free on your Mac. Either search specifically for conferences, talks, speakers or topics or simply browse through the catalog - you can add talks to your watchlist to save for later, favourite or continue watching where you left off.

Add Conferences.digital

---

applications.json

Adding ElectronMail.
https://github.com/vladimiry/ElectronMail
Email
Unofficial desktop app for ProtonMail and Tutanota end-to-end encrypted email providers 
The app provides unique features that are not supported by the official in-browser web clients. Such as for example offline access to the email messages, full-text search (fully functional in offline), multiple accounts support, automatic login, and many more (see [readme](https://github.com/vladimiry/ElectronMail/blob/master/README.md) file for details).

add ElectronMail

---

applications.json

https://github.com/Ji4n1ng/OpenInTerminal
Finder, Terminal
✨ Finder Toolbar app for macOS to open the current directory in Terminal, iTerm or Hyper.

Add OpenInTerminal

---

applications.json

https://github.com/agalwood/Motrix
Downloader
Motrix is a full-featured download manager that supports downloading HTTP, FTP, BitTorrent, Magnet, Baidu Net Disk, etc.

Add Motrix

---

applications.json

https://github.com/macmade/Notarize
Development
Add Notarize a Notarization status monitoring tool for macOS, supporting multiple developer accounts.

Add Notarize

---

applications.json

https://github.com/nsriram/KubeSwitch
Web development
KubeSwitch lists the available kubernetes cluster contexts on the mac, in Mac's Menu bar. Using KubeSwitch users can
* View available kubernetes cluster contexts on their Mac
* View the current selected kubernetes cluster context
* Change the current selection for kubernetes cluster context
Its an effective utility for Kuberenetes Users to switch between contexts

Add KubeSwitch

---

applications.json

https://github.com/turkenh/KubeContext
Menubar
Adding KubeContext
A small menu bar app for managing Kubernetes contexts.
Easily switch between contexts
Import/export contexts from/to kubeconfig files
Context name in menu bar
Assign colors to your contexts
Easy context management UI for renaming context, setting namespace and more.

Add KubeContext

---

applications.json

[https://github.com/friedrichweise/wechsel](https://github.com/friedrichweise/wechsel/)
Utilities
Adding wechsel
wechsel (/ˈvɛksəl/) claims to simplify the interaction with bluetooth connections on macOS. Instead of using the builtin Bluetooth menu bar, you can seamlessly switch between bluetooth audio devices using your keyboard. The tool offers a global hotkey to display a Spotlight-like window.

Add wechsel

---

applications.json

https://github.com/CD1212/Doughnut
Podcast
Added the Doughnut podcast app. The design and user experience are inspired by Instacast for Mac which was discontinued in 2015.

Add Doughnut

---

applications.json

https://github.com/LumingYin/Caption
Video
Transcribe and generate caption files (SRT, ASS and FCPXML) without manually entering time codes.
Quick Caption empowers content creators to make their videos more accessible.

Add Quick Caption to applications.json.

---

applications.json

https://github.com/dragstor/mac-sound-fix
Utilities
Simple app made to fix the sound issues (it going mute and not responsive to controls) that can happen while using an external HDMI monitor on macOS or while attaching/detaching headphones.
Because it's open sourced and it's useful 😄

Added macOS sound re-enabler

---

applications.json

Signed-off-by: Clovis Durand <cd.clovel19@gmail.com>
https://github.com/mikebrady/shairport-sync
Audio
Added Shairport Sync Airplay audio receiver project to the application list
This software is a great one to have an airplay audio receiver.

Added Shairport Sync Airplay audio receiver to applications.json

---

applications.json

Main site: https://httptoolkit.tech/
Github org: https://github.com/httptoolkit/
Web Development
HTTP Toolkit is a 100% open-source app, built with TypeScript & Electron, that works beautifully on MacOS (in addition to other platforms). It's a broad spectrum suite of HTTP tools, to intercept, debug & mock any HTTP and HTTPS traffic.
It's a popular, open-source & awesome tool.
Yes, although there are a few parts. There's the [desktop app](https://github.com/httptoolkit/httptoolkit-desktop) (which I've used as the main repo here), [the server](https://github.com/httptoolkit/httptoolkit-server) & [the UI](https://github.com/httptoolkit/httptoolkit-ui). Each has a readme on the technical details of the component and how they relate, and each links to https://httptoolkit.tech/ which explains …

Add HTTP Toolkit to applications

---

applications.json

https://github.com/jhspetersson/fselect
Utilities
Command-line utility to search files with SQL syntax.
It's a decent replacement for classic `find` in some cases.

add jhspetersson/fselect

---

applications.json

Seems to have been erroneously placed in the git category.

Move MessagesHistoryBrowser to chat category

---

applications.json

* https://github.com/ExistentialAudio/BlackHole
* Audio
Add BlackHole to `applications.json`, a modern MacOS virtual audio driver.
Anyone recording podcasts or screencasts on MacOS will at some point want to capture audio from another app, or setup background music of some sort. This works on the latests version of MacOS and is simple to use and install.

Add BlackHole for modern audio routing

---

applications.json

https://github.com/federico-terzi/espanso
Productivity
A Cross-platform, System-Wide Text Expander written in Rust. Replaces text with something else while typing, boosting productivity.
This represents a valid and open-source alternative to the very popular Alfred's Snippets feature.

Add espanso

---

applications.json

https://github.com/doches/lilypond-ui
Either **Music** or **Editors**, as it's an editor for typesetting music.
Straightforward addition of a JSON block, in the specified format, that adds the app above.
Because it's an easy-to-use app for working with a notoriously hard-to-use tool, and music typesetting is a niche that's currently unrepresented on this list.

Add Lilypond UI, an IDE for typesetting musical scores.

---

applications.json

https://github.com/nikolaeu/Numi
Utilities
I added the Numi open source calculator app to the list of applications.

Add Numi to list of applications

---

applications.json

Added the audio application with winamp like interface "cog"
https://kode54.net/cog/
Audio
Added the audio application with winamp like interface "cog" to aplications.json
Great low memory application, esp if you want to manage your music in folders

Update to include audio application cog

---

applications.json

https://github.com/spieglt/flyingcarpet
Utilities
Adding one project
People would sometimes like to exchange files with other laptops without needing WiFi or uploading files to the cloud unnecessarily.

Adding Flying Carpet to utilities

---

applications.json

Though really Homebrew and Homebrew Cask should be their own "type"
Closes #315
Add Mac Homebrew Cask to Utilities
https://brew.sh
Utilitiy
Add Mac Homebrew Cask to Utilities
In my opinion, [Homebrew](https://github.com/Homebrew/homebrew-core) and [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) should be their own category and I am happy to add another PR

Add Mac Homebrew Cask to Utilities

---

applications.json

Audacity is a free and open-source digital audio editor and recording application software, available for Windows, macOS/OS X and Unix-like operating systems
https://www.audacityteam.org/
Music
Audacity is a free and open-source digital audio editor and recording application software, available for Windows, macOS/OS X and Unix-like operating systems

Add Audacity

---

applications.json

https://github.com/spieglt/cloaker
Security
Adding Cloaker to the security section
People need a very simple way to encrypt files with a password. Legacy zip encryption is insecure and PGP is notoriously difficult to use.

Adding Cloaker to security section

---

applications.json

The repository found at https://github.com/brave/browser-laptop has been archived by the owner. It is now read-only. 
Its description reads:
> [DEPRECATED] Please see https://github.com/brave/brave-browser for the current version of Brave
This pull request features one commit that updates the Brave Browser URL in applications.json to point directly to the current Brave repository.

Updated Brave Browser URL in applications.json

---

applications.json

Oni and Quickwords had an additional `![javascript]` inside the `short_description` field, leading to duplicated icons. This PR removes the duplicates, relying exclusively on the `languages` field to set language icons.
- Addresses #448

Remove duplicate language icons for Oni and Quickwords (#448)

---

applications.json

- JSON maintenance: Project description contained a duplicate `short_description` line, so I took out the extra one.

Remove duplicate description tag in Iina app

---

applications.json

https://github.com/larson-carter/android-messenger-mac/blob/master/README.md
Chat
- Wrapper doesn't work anymore as stated by the original maintainer.

Remove Android Messenger for Mac

---

applications.json

- multiple apps were using `typescript` inside the `languages` field, which would not render correctly
- this changes all instances to `type_script`

Fix typescript icons for multiple apps

---

applications.json

https://github.com/bow-swift/nef-plugin
Extensions
This project provides an extension for Xcode to integrate some nef features directly in the IDE. Using the core of nef, you can export snippets from your code selection directly in Xcode.
You know all of those code screenshots you see on social networks, or at meetups and conferences? Do you want to share images of your code with your team? This Xcode extension makes it easy to create and share beautiful images of your source code.

Add nef Xcode extension to list

---

applications.json

Adding Sessions
https://github.com/AlexPerathoner/Sessions
Productivity, Extensions 
Simple Safari Extension to save and organise your working sessions.
Imagine you are working on a project. Then you suddenly switch project. You don't want the tabs you were using before to be open anymore. But you also don't want to close them, as you'd have to re-open them later. So what do you do? You use sessions!

Added Sessions

---

README.md
applications.json

Here is quite from repo: 
> **⚠️ Nylas Mail was initially released and open-sourced in early 2015 and was maintained by Nylas until Spring 2017.** While Nylas no longer supports Nylas Mail, you can download the latest release or build it from source. There are also **[several forks](#forks)** that are being actively developed and maintained.

Replace Nylas to the newer version 

---

applications.json

https://www.qownnotes.org/
Markdown, Notes, Productivity
Plain-text file notepad and todo-list manager with markdown support and ownCloud / Nextcloud integration.

Add QOwnNotes

---

applications.json

https://github.com/buzzfeed/Sketch-Toolbox
Grpahics
Remove Sketch Toolbox because it has been deprecated.

Remove Sketch Toolbox entry (deprecated)

---

applications.json

https://github.com/overtake/telegram
Chat
Removes Telegram's deprecated entry on `applications.json`

Remove Telegram's deprecated entry

---

applications.json

In `applications.json` there was a category in sentence case for Strategr: it was `"Productivity"` instead of `"productivity"`. Apparently, it couldn't be parsed correctly and was left out of README.

Fixes sentence case in the category for Strategr

---

README.md
applications.json

Emulate a scroll wheel click with three finger Click or Tap on MacBook trackpad and Magic Mouse with macOS Catalina10.15 support!
https://github.com/DaFuqtor/MiddleClick-Catalina
productivity, utilities, extensions
This is what I was missing using (great btw) trachpad in mac

Add Middleclick

---

applications.json

Add Swifty password manger
http://getswifty.pro
Security
Update `applications.json` to add Swifty password manager to the list of apps and security category

Add Swifty password manager

---

applications.json

Add Ultra TabSaver to the list of apps.
https://github.com/morsamatias/UltraTabSaver
Extensions
open source Tabs Manager for Safari.
There isn't any other Tab Manager open source for safari.

Add Ultra TabSaver

---

applications.json

https://github.com/instance01/mac-screenshot-tracker
Productivity
Become more productive by reviewing what you've been working on. This application runs in the background and creates low-resolution screenshots every 60 or so (can be changed) seconds. After a tough day full of work you can then watch what you've been doing. Maybe you find that you waste a surprisingly huge amount of time on random things.
It's a completely free alternative to the many screenshot trackers out there. It is very simple and hackable. It gets the job done!

Add Mac Screenshot Tracker

---

applications.json

https://github.com/billthefarmer/ctuner
Audio
I have added an entry for my Tuner app. Note there are five versions of this app, four in this repository &ndash; windows, linux, old macOS using C, new macOS using Swift. The README for the Swift version is in https://github.com/billthefarmer/ctuner/tree/master/swift. And an android version https://github.com/billthefarmer/tuner.
You don't appear to have a macOS tuner app. I also have macOS signal generator and oscilloscope apps which I will add.
- [ x ] Edit [applications.json](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/applications.json) instead of [README.md](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/README.md).
- [ x ] Only one project/change is in this pull request
- [ x ] …

Add tuner app

---

applications.json

Added new JSON to Model class generator app in JSON Parsing section
https://github.com/chanonly123/Json-Model-Generator
json-Parsing
Only one change in readme.md file, just added my new app "JSON to Model class generator"
This app uses template to generate model classes, so it is highly customisable and also supports templates created by user. Also supports many languages.

Added new mac app for JSON to model class generator

---

applications.json

https://github.com/rkbhochalya/grayscale-mode
- `utilities`
- `menubar`
Grayscale Mode is a macOS app that lets you quickly toggle grayscale filter right from your menu bar or using a keyboard shortcut (⌥⌘G).

Add Grayscale Mode

---

PULL_REQUEST_TEMPLATE.md
applications.json

http://netbeans.apache.org
IDE, development
NetBeans is both an IDE and a platform for development. NetBeans is an integrated development environment (IDE) for Java, PHP, C, C++, HTML5,[4] and JavaScript. The NetBeans Platform is a framework for simplifying the development of Swing desktop applications. The NetBeans IDE bundle for Java SE contains what is needed to start developing NetBeans plugins and NetBeans Platform based applications; no additional SDK is required.
NetBeans has been accepted by Apache as a top-level project. It has a stable and engaged development community who have been driving development of the application for many years. There is a supportive community for new and experienced users. All Apache NetBeans source code is freely available to build yourself, or you can …

Suggest Apache NetBeans as a candidate

---

applications.json

This PR adds the tiling window manager Yabai to the application-list.
https://github.com/koekeishiya/yabai
window-management
This PR creates a JSON Entry in the `applications.json` file.
I personally like tiling window managers, because they help me organise (it's more the way I think). Thus, I would like to give this project some credit by this PR.

Window-Manager Yabai

---

applications.json

https://github.com/joshjon/nocturnal
- `utilities`
- `menubar`
Nocturnal is an open-source app that is great for people who have sensitive eyes. It lets you apply darker than dark dimming, fine tune Night Shift temperature, completely turn off TouchBar on Macbook Pro, and supports multi-screen setups.

Add Nocturnal

---

applications.json

CoreLocationCLI
Utility
CoreLocationCLI gets the physical location of your device and prints it to standard output. If you move it can also print your updated location.
In case you forget where you are.

Add CoreLocationCLI

---

applications.json

This is a simple useful tool for users which allow you to do the following:
Show GateKeeper Status.
Enable GateKeeper.
Disable GateKeeper.
Remove app from GateKeeper quarantine.
Self-sign the app.
https://github.com/wynioux/macOS-GateKeeper-Helper
System, Utilities, Security and Terminal
Add Add macOS GateKeeper Helper in applications.json
It helps you to control your GateKeeper.

Add macOS GateKeeper Helper

---

applications.json

(also removed a trailing comma that made the JSON technically invalid)
https://github.com/bhj/karaoke-forever
- Audio
- Music
Host awesome karaoke parties where everyone can queue songs from their phone's browser. Plays MP3+G and MP4 with WebGL visualizations.
It's been listed over at [awesome-selfhosted](https://github.com/awesome-selfhosted/awesome-selfhosted) for a while but it needs to be on more platform-specific lists as well.

Add Karaoke Forever

---

applications.json

https://github.com/insidegui/NoiseBuddy
- audio
- music
- menubar
- utilities
Control the listening mode on your AirPods Pro in the Touch Bar or Menu Bar.

Add NoiseBuddy app to the list

---

applications.json

https://github.com/Sequel-Ace/Sequel-Ace
database
Adding Sequel Ace to the list since Sequel Pro is not maintained anymore.

Sequel ace

---

applications.json

- Ao: the website hosting the screenshots has gone away
- KeepingYouAwake: was missing a @2 at the end of the filename
- The Unarchiver: No open source repo. Actually a closed source MacPaw product.
- Spotter: Put repo link in the wrong category
- Strategr: Moved to StrategrDesktop page of khrykin.github.io
- QOwnNotes: Screenshot location moved on website
Every pull request is receiving a message saying these issues needed to be resolved.

Resolve All Link Warnings

---

applications.json

https://github.com/robaho/seashore
images
It is a simple image editor based on GIMP.
There are not many images editors listed AFAIK.

Add seashore, image editing for macOS

---

applications.json

https://github.com/pedrommcarrasco/Brooklyn
Screensaver
Screensaver inspired by Apple's Event on October 30, 2018
It is a well-made and visually interesting screensaver with 4.2k stars on Github.

Add Brooklyn Screensaver

---

applications.json

This is a followup PR to fix an issue in my recently merged PR that added Itsycal: https://github.com/serhii-londar/open-source-mac-os-apps/pull/585. I forgot to change the title after doing my Hidden Bar PR.

Fix Itsycal mistake in title

---

applications.json

Add RedditOS macOS project.
https://github.com/Dimillian/RedditOS
Social Networking
A SwiftUI Reddit client for macOS.
This is bleeding edge, you need macOS Big Sur beta and Xcode 12 beta.

Add RedditOS

---

applications.json

https://github.com/powerwolf543/DuplicateFinder
- `finder`
- `utilities`
It's a useful tool that would help you to find all duplicate files which have the same names in the specific folder.

Add Duplicate Finder

---

applications.json

- GitHub: https://github.com/hisaac/PlainPasta/
- Webpage: https://hisaac.github.io/PlainPasta/
Utilities
- Fix indentation in CONTRIBUTING.md
- Add Plain Pasta to applications.json
This is a little Swift app that I've open-sourced. Everyone who uses it seems to like it, and I'd love for more people to check it out.

Add Plain Pasta

---

applications.json

Closes #295 
https://github.com/DigiDNA/ColorSet
Development, graphics
ColorSet is a macOS utility and framework allowing developers to manage custom interface colors with ease.

Added ColorSet - Fixes #295

---

applications.json

https://github.com/Bunn/PiStats
Menubar
macOS app to visualize Pi-hole information.

Add Pi Stats

---

applications.json

https://github.com/fand/json-editor-app
Editors -> JSON
Dead simple JSON editor using josdejong/jsoneditor.
This is a simple JSON editor.
I usually use it in masOS. I created a PR to add it here because it's useful.

Add JSON Editor

---

applications.json

Add an entry for [Bitwarden Menu](https://github.com/jnsdrtlf/bitwarden-menubar), a simple application for macOS that puts the Bitwarden Browser Extension right into your menu bar.
https://github.com/jnsdrtlf/bitwarden-menubar
Utilities
Simple application for macOS that puts the Bitwarden Browser Extension right into your menu bar.

Add Bitwarden Menu

---

applications.json

Adds Rocket Chat
https://github.com/RocketChat/Rocket.Chat.Electron
Chat
Free open source chat system for teams. An alternative to Slack that can also be self hosted.
Good open source projects including meteor server, electron apps and reactive-native apps.

Add RocketChat

---

applications.json

https://github.com/ffittschen/IsItPrivate
Extensions
Adds the _Is It Private?_ Safari extension.
It is built as [Safari App Extension](https://developer.apple.com/documentation/safariservices/safari_app_extensions), which can be interesting for other developers who want to create a Safari extension.

Add Is It Private

---

applications.json

https://github.com/87kangsw/ThenGenerator
extensions, productivity, utilities
Xcode Source Editor Extension for [Then](https://github.com/devxoul/Then)

Add ThenGenerator

---

applications.json

https://github.com/relikd/barss
news, menubar, utilities
RSS & Atom feed reader that lives in the system status bar.

baRSS menu bar news reader

---

applications.json

Added [AltTab](https://github.com/lwouis/alt-tab-macos)
https://github.com/lwouis/alt-tab-macos
Window Management
**AltTab** brings the power of Windows alt-tab to macOS
This application is very handy for developers, is open source, and is actively being updated

Added AltTab

---

applications.json

This is PR adds an Objective C app under the screensaver section. It is a neat screensaver which shows the current time in the format of the Unix timestamp, on a flip clock. Full credit to  by @chrstphrknwtn
https://github.com/chrstphrknwtn/epoch-flip-clock-screensaver
Screensaver
This is a MacOS screensaver by @chrstphrknwtn, which shows the current time in the format of the Unix timestamp, on a flip clock.
Because it's a neat MacOS app

Adds Unix Epoch Flip Clock under Screensavers

---

applications.json

[Stringz](https://github.com/mohakapt/Stringz)
Development, iOS/macOS, Utilities
Stringz greatly simplifies localizing your Xcode apps (iOS, macOS, tvOS, and watchOS) by introducing a powerful editor for all localizable files in your project. It even imports strings from storyboard and xib files saving you a lot of time and effort finding and matching elementIds in your storyboards. Stringz also supports localizing your Info.plist file so you can easily translate your app name and permission descriptions.
Stringz will also highlight missing translations and warn you about duplicate values and has many more useful features that take a painful and tedious task like localizing your app and convert it to an easy and simple task.
The app is a life saver when working on international projects, …

Adding Stringz

---

applications.json

N/A
N/A
I removed the Mockup Generator, as the project was deleted from Github. It's certainly possible there's a replacement/fork of it, so it's probably a good idea to look for one.
Also, sorry if I'm doing anything wrong, I don't have much experience with pull requests or commits.
N/A

Removed Mockup Generator as the project was deleted.

---

applications.json

https://opensource.apple.com/source/Chess/Chess-410.4.1/
Games
Added the default Chess.app app that comes with macOS.
Because it's cool that Apple open sourced this, and it's still included with macOS. Most people don't know that it's open source.

Add Chess.app

---

applications.json

https://github.com/sindresorhus/Pasteboard-Viewer
Development
This is a developer utility that lets you inspect the various system [pasteboards](https://developer.apple.com/documentation/appkit/nspasteboard).
When developing an app that has copy/paste functionality, it's very useful to be able to see exactly what is being copied. It can also be useful to debug bugs in app you use. You could even use it to debug copying content from web apps. Let's say your app let the user copy an image, you could use this app to ensure it's copied in the correct format.

Add Pasteboard Viewer

---

applications.json
categories.json

https://github.com/mifi/lossless-cut
`audio`
`video`
The swiss army knife of lossless video/audio editing.e
No need to re-encode video or audio and saving disk space.
iMovie will re-encode the video that taking a lot of disks space and time.
Sometimes we only need some simple features like cutting or merge video files.
LosslessCut is an excellent option to achieve that.

Add LosslessCut

---

README.md

This PR is to fix unrendered shell icon in readme file.

fix: resolve unrendered shell icon

---

applications.json

https://github.com/adguardteam/adguardforsafari
Extensions
AdGuard is an open-source freemium Safari adblocker.
I had been looking for an equivalent to uBlock Origin for Safari and found AdGuard to be roughly on par with it. It has a point-and-click functionality for zapping ads that slip through, but I've found this to be rare. Overall, it's a great adblocker that also doesn't break functionality on most sites, like YouTube or search engines.

feat: Add AdGuard for Safari

---

applications.json

https://cyberduck.io
Sharing Files
Added Cyberduck in Sharing-Files section. It's a libre server and cloud storage browser for Mac.
There is no such software in list.

Add Cyberduck in Sharing-Files section

---

applications.json

https://github.com/halo/LinkLiar
Menubar
(I was considering creating the categories "Networking" and "Privacy". What do you think?)
LinkLiar is an intuitive open-source macOS status menu application written in Swift to help you spoof the MAC addresses of your Wi-Fi and Ethernet interfaces.
I noticed that [Airpass](https://github.com/alvesjtiago/airpass) (written in JS) is in the list. LinkLiar is similar but runs natively and has a few more features. So, it fits right in.
Thank you for your time. This is a useful list! 🤩

Add LinkLiar (menubar app for MAC spoofing)

---

applications.json

https://github.com/thamara/time-to-leave
Productivity
Time to Leave is a Desktop app for work time management which looks similar to a time-card system. It’s different from other software available as it’s very simple, doesn’t require any database configuration, and focuses on allowing you to control your time. Its premise is to help you manage the time you are working and to notify you when it’s time to leave (hence the name).

Add Time to leave

---

applications.json

https://gitlab.com/kicad/code/kicad
Development
Add KiCAD EDA Suite
Also removed unnecessary trailing commas in the json
KiCAD is a really useful and well-known tool for designing and exporting electrical schematics and printed circuit boards.

Added KiCad

---

applications.json

https://gitlab.com/inkscape/inkscape
Images
Adding Inkscape to the Images category

Add Inkscape to Images Category

---

applications.json

Added OpenRocket to the utilities section.
https://github.com/openrocket/openrocket and https://openrocket.info/
Utilities
I added an entry to the applications.json that adds OpenRocket under the utilities section. 
OpenRocket is a free, open-source alternative to some other rocketry simulation software. The program is cross-platform and super useful for simulating the characteristics of a model rocket under different situations. I hope you find this program as interesting as I do!

Added OpenRocket

---

applications.json

https://github.com/serhii-londar/open-source-mac-os-apps/
utilities
Changed 'Passwort' to 'Password' in the short_description field.

Fixing typo in the Bitwarden Menu entry

---

applications.json

https://github.com/serhii-londar/open-source-mac-os-apps/
utilities
Changed 'parcents' to 'percents' in the short_description field.

Fixing typo in the PercentCalculator entry

---

applications.json

https://github.com/elfmz/far2l
utilities, productivity
Linux/Mac fork of FAR Manager v2 (http://farmanager.com/)
Plug-ins that are currently working: NetRocks (SFTP/SCP/FTP/FTPS/SMB/NFS/WebDAV), colorer, multiarc, tmppanel, align, autowrap, drawline, editcase, SimpleIndent, Calculator, Python (optional scripting support)
This is a pretty good fork of a classical must-have two panels file managers from the windows world

Add far2l fork of FAR Manager

---

applications.json

1. Removed the following discontinued applications: LifeCalendar, Ferdi and Music Bar.
2. Removed EtreChec and Vercil  because the repository is not public anymore. 
3. Updated screenshot of Iconology and Beagle IM (previous entries 404 not found).
4. Pointed links with HTTP 301/302 to their new location.

Remove discontinued and closed-source applications, update HTTP 301/302 links

---

applications.json

https://github.com/ThijmenDam/BarTranslate
Menubar
BarTranslate, a handy menubar translator app using Google Translate.
I use BarTranslate almost everyday, and thus I think someone else might find it useful too! It provides quick access to Google Translate and supports numerous keyboard shortcuts to make translating anything quick and easy,.

BarTranslate, a handy menubar translator app.

---

applications.json

https://github.com/okwasniewski/MiniSim
Menubar
MiniSim is a small utility menu bar app for launching Android 🤖 and iOS  emulators (and more!).
Written in Swift and AppKit.

Add MiniSim app

---

applications.json

https://github.com/ChimeHQ/Chime
Editors
Built for macOS
Chime was designed to be a model citizen on the Mac. Even its extensions are native.

Add Chime app

---

applications.json

https://github.com/MarkEdit-app/MarkEdit
markdown
MarkEdit is a free and open-source Markdown editor, for macOS. It's just like TextEdit on Mac but dedicated to Markdown.

Add MarkEdit app

---

applications.json

Added the opensource podcast aggregator gPodder.
[https://github.com/gpodder/gpodder](https://github.com/gpodder/gpodder)
Podcast
Added a new entry to the applications.json by adding the information for gPodder

Added gPodder

---

applications.json

Add TimeScribe - Open-Source Time Tracking for Mac Users
[TimeScribe](https://timescribe.app/)
Productivity, Menubar
TimeScribe is an open-source time-tracking application designed specifically for Mac users. It offers a user-friendly interface to track work hours, manage breaks, and categorize app activities. Key features include easy time tracking, automatic break management, app activity monitoring, absence tracking, and auto start/break functionality based on computer usage or specified times. The project aims to provide a free, community-driven alternative to paid time-tracking solutions.
TimeScribe fills a gap in the open-source ecosystem by providing a robust, user-friendly time-tracking solution tailored for Mac users. Its features are on par with paid alternatives, making it a …

Add TimeScribe
